### ISSUE TITLE
[TYPO] KEY: "proriority" here is misspelled or on purpose?

### ISSUE THREAD

**Issue by W3stside** [gnosis/gnosis-management#89]
https://github.com/gnosis/gnosis-management/blob/0b24090bb9d5178d36157660d4e8c205531a1976/src/integrations/metamask/index.js#L22

**Comment by mmvsha** [comment]
@andre-meyer

**Comment by andre-meyer** [comment]
Solved in latest hotfix https://github.com/gnosis/gnosis-management/commit/2be1b4afd11f88baf87bc880906fe687e3a463f3

You saw nothing 🙈
